config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" unless Rails.env.production?

  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    unlocks:            'users/unlocks',
    passwords:          'users/passwords'
  }

  resources :events do
    resources :lists, only: [:index, :show] do
      collection do
        get :feed
      end

      member do
        get :claim
      end
    end
    
    resources :families do
      member do
        put :lists_complete
        get :confirmation
      end

      resources :lists
    end

  end

  resources :sponsors

  namespace :admin do
    resource :settings
    resources :sponsors
    resources :users, only: [:index]
    resources :ahoy_visits, only: [:index], path: 'visits'
    resources :ahoy_events, only: [:index], path: 'ahoy_events'
    resources :events do
      member do 
        get :cheatsheet
      end
    end
    resources :lists do
      member do
        put :remove_sponsor
      end
    end
    resources :list_items
    resources :families
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
end

app/models/list.rb
class List < ApplicationRecord
  include PgSearch::Model
  extend FriendlyId
  friendly_id :alias, use: :slugged

  belongs_to :family
  belongs_to :sponsor, optional: true

  has_many :list_items, dependent: :destroy

  accepts_nested_attributes_for :list_items, allow_destroy: true

  scope :published,   -> { where(is_published: true) }
  scope :pending,     -> { where.not(is_published: true) }
  scope :sponsorable, -> { published.where(sponsor_id: nil) }
  scope :sponsored,   -> { published.where.not(sponsor_id: nil).order(sponsored_at: :desc) }

  pg_search_scope :contains,
                  against: [
                    :name,
                  ],
                  using: { tsearch: { prefix: true } }

  validates :name,            presence: true
  validates :age,             presence: true
  
  validate :_prevent_update_if_published

  before_save :_ensure_alias

  def status
    if is_published
      'published'
    else
      'pending'
    end
  end

  def family_name
    family&.name
  end

  def event_name
    family&.event&.name
  end

  def list_items_count
    list_items.count
  end

  def sponsor_name
    sponsor&.full_name
  end

  def remove_sponsor!
    update(sponsor_id: nil)
  end

  def self.to_csv
    attrs = [
      "id",
      "name",
      "alias",
      "event_name",
      "family_name",
      "age",
      "gender",
      "gift_card_store",
      "list_items_count",
      "created_at",
      "is_published",
      "sponsor_name",
    ]

    CSV.generate do |csv|
      csv << attrs
    
      all.each do |family|
        csv << attrs.map {|attr| family.send(attr)}
      end
    end
  end

  def _ensure_alias
    return if self.alias.present?

    until self.alias.present? && List.where(alias: self.alias).empty?
      self.alias = SecureRandom.random_number(1_000..9_999).to_s
    end
  end

  def _prevent_update_if_published
    if is_published
      errors.add(:base, "Cannot update a published list")
      false
    end
  end
end

app/controllers/admin/lists_controller.rb
class Admin::ListsController < Admin::BaseController
  before_action :_set_list, only: [:show, :edit, :remove_sponsor, :update, :destroy]

  def index
    @page_title = "Wishlists"
    @lists      = List.all
    @lists      = @lists.send(params[:scope]) if params[:scope].present?
    @lists      = @lists.contains(params[:q]) if params[:q].present?
    
    if params[:family_id].present?
      @family = Family.friendly.find(params[:family_id])
      @lists      = @lists.where(family_id: @family.id)
    end

    respond_to do |format|
      format.html
      format.csv { send_data @lists.to_csv }
    end
  end

  def show
    @page_title = @list.name
  end

  def edit
    @page_title = 'Edit Wishlist'
  end

  def remove_sponsor
    @list.remove_sponsor!

    redirect_to admin_lists_path(), notice: "Sponsor removed successfully"
  end

  def update
    if @list.update(list_params)
      redirect_to edit_admin_list_path(@list), notice: "Wishlist updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy

    redirect_to admin_lists_path, notice: "Wishlist deleted successfully"
  end

  private

  def _set_list
    @list = List.friendly.find(params[:id])
  end

  def list_params
    params.require(:list).permit(
      :name,
      :age,
      :gender,
      :gift_card_store,
      :is_published,
      :alias, 
      list_items_attributes: [
        :id,
        :name,
        :url,
        :_destroy
      ]
    )
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :_check_api_key, only: %i[ feed ]
  before_action :_set_event
  before_action :_set_family, except: %i[ index show claim feed ]
  before_action :set_list, only: %i[ show edit update destroy claim ]

  def index
    @lists = List.sponsorable

  end
  
  def feed
    @lists = List.sponsored
    
    respond_to do |format|
      format.json
    end
  end

  def show
  end

  def claim
    if session[:sponsor_id].present? && Sponsor.exists?(session[:sponsor_id])
      @list.update(
        sponsor_id: session[:sponsor_id],
        sponsored_at: Time.now
      )

      redirect_to event_list_path(@event, @list), notice: "Wishlist was successfully claimed."
    else
      session[:redirect_url] = claim_event_list_path(@event, @list)

      redirect_to new_sponsor_path
    end
  end

  def new
    @list = List.new
    @list.list_items.build
  end

  def edit
  end

  def create
    @list = @family.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to new_event_family_list_path(@family.event, @family), notice: "List was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to new_event_family_list_path(@family.event, @family), notice: "List was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(
        :family_id,
        :name,
        :age,
        :gender,
        :is_qualified,
        :qualification_criteria,
        :gift_card_store,
        list_items_attributes: %i[id name url _destroy]
      )
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= simple_form_for([@event, @family, @list]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class='card'>
    <% if defined?(title) %>
      <div class='card-header'>
        <h1><%= title %></h1>
      </div>
    <% end %>

    <div class='card-body'>
      <% if defined?(description) %>
        <p><%= description %></p>
      <% end %>

      <div class='field'>
        <%= f.input :name, input_html: { class: 'form-control' }, label: "Child's Name" %>
      </div>

      <div class='field'>
        <%= f.input :age, collection: 0..24, input_html: { class: 'form-control' }, label: "Child's Age" %>
      </div>

      <div class='field'>
        <%= f.input :gender, as: :radio_buttons, collection: ['male', 'female', 'nonbinary'], label: "Child's Gender" %>
      </div>

      <div class='field'>
        <%= f.input :qualification_criteria, as: :radio_buttons, collection: ["Yes, this child is in foster care", "No, this child is adopted", "No, this child is my biological child"], label: "Is child in foster care?", include_blank: "Select an option" %>
      </div>

      <div class='field'>
        <%= f.input :gift_card_store, input_html: { class: 'form-control' }, label: 'Where would your child be excited to get a gift card from?' %>
      </div>

      <h2>Items</h2>
      <p>Please be as specific as possible when filling out the form for each child in your household! We will aim to get the exact items requested, but may get ones that are similar in nature (e.g. American Girl Doll is requested, Truly Me doll is provided).</p>
      <%= f.association :list_items do |li| %>
        <%= render 'list_item_fields', f: li %>
      <% end %>

      <%= link_to_add_fields "Add Item", f, :list_items %>
    </div>

    <div class="card-footer">
      <%= f.button :submit, 'Submit Wishlist', class: 'btn btn-primary btn-lg w-100' %>
    </div>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>Family:</strong>
    <%= list.family_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= list.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= list.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= list.gender %>
  </p>

  <p>
    <strong>Gift card store:</strong>
    <%= list.gift_card_store %>
  </p>

</div>

app/views/lists/edit.html.erb
<div class='container w-md'>
  <%= render "form", list: @list, title: "Edit #{@list.name.titleize}" %>
</div>

app/views/lists/index.html.erb
<div class='container w-lg text-center'>
  <h1>Sponsor a Holiday Wishlist</h1>

  <p class='py-3'>
    We're excited that you would like to support children, youth, and families experiencing foster care this holiday season! Please select one of more youth below that you are committed to supporting. We ask that the total gifts be valued at <u>$100 per child</u> and that the gifts arrive to us by <u>December 2nd</u>. Gifts can be delivered or shipped to the Atlanta Angels office (2555 Northwinds Pkwy, Alpharetta, GA 30009.) Thank you for your help in making this a memorable holiday season!
  </p>

  <div class='card'>
    <div class='card-header'>
      <p class='mb-0'>
        <em><%= pluralize(@lists.count, 'wishlist') %> remaining (of <%= pluralize(List.published.count, 'wishlist') %>)</em>
      </p>
    </div>

    <div class='card-body px-3'>

      <table class='table text-start mb-4'>
        <thead class='sticky-top'>
          <tr>
            <th>Child Alias</th>
            <th class='text-center'>Gender (Age)</th>
            <th class='text-center'>Location</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @lists.each do |list| %>
            <tr>
              <td>
                <%= list.alias %>
              </td>
              <td class='text-center'>
                <%= list.gender %> (<%= list.age %>)
              </td>
              <td class='text-center'>
                <%= list.family.address %>
              </td>
              <td class='text-end'>
                <%= link_to 'View Wishlist', event_list_path(@event, list), class: 'btn btn-primary' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class='container w-md'>
  <% if @family.lists.any? && params[:hide_review].nil? && params[:action] == 'new' %>
    <div class='card mb-4'>
      <div class='card-header'>
        <h2>Review Wishlists</h2>
      </div>
      <div class='card-body'>
        <p>Please review wishlists and confirm you have submitted a wishlist for all children. Once you are done, click “Complete”</p>

        <h3>Wishlists</h3>
        <table class='table'>
          <thead>
            <tr>
              <th>Child</th>
              <th class='text-center'>Age</th>
              <th class='text-center'>Items</th>
              <th class='text-right'></th>
            </tr>
          </thead>
          <tbody>
            <% @family.lists.each do |list| %>
              <tr>
                <td><%= list.name %></td>
                <td class='text-center'><%= list.age %></td>
                <td class='text-center'><%= list.list_items.count %></td>
                <td class='text-end'>
                  <%= link_to 'Edit', edit_event_family_list_path(@family.event, @family, list), class: 'btn btn-outline-primary btn-sm' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class='card-footer'>
        <div class='row'>
          <div class='col-6'>
            <%= link_to 'Add New Wishlist', url_for(hide_review: true), class: 'btn btn-outline-secondary w-100 btn-lg' %>
          </div>
          <div class='col-6'>
            <%= form_for @list, url: lists_complete_event_family_path(@event, @family, @list), method: :put do |f|%>
              <%= submit_tag "Complete", class: 'btn btn-primary w-100 btn-lg'  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <%= render "form", list: @list, title: 'New Wishlist', description: "If you need support providing holiday gifts this holiday season, we are excited to help. We will support up to $100 per child. If you have an item request that is more than $100, we recommend requesting a gift card to go towards it. IMPORTANT: We will try our best to fulfill every wishlist item requested, but we will be prioritizing youth currently in care depending on resources available." %>
</div>

app/views/lists/show.html.erb
<div class='container w-md text-center'>
  
  <%= link_to 'View All Wishlists', event_lists_path(@event), class: 'btn btn-outline d-block mb-4' %>

  <div class='card'>
    <div class='card-header'>
      <h1><%= @list.alias %> <em class='text-muted small lead'>(alias)</em></h1>
    </div>
    <div class='card-body'>

      <% unless @list.sponsor.present? %>
        <p class='lead'>
          This wishlist is for a <%= @list.gender %> child (<%= @list.age %>) living in <%= @list.family.address %> County.
          By claiming this wishlist, you are committing to spend $100 and deliver or ship the gifts to our Alpharetta office by December 2nd.
        </p>

        <table class='table text-start'>
          <thead>
            <tr>
              <th>Item Name</th>
            </tr>
          </thead>
          <tbody>
            <% @list.list_items.each do |list_item| %>
              <tr>
                <td>
                  <%= list_item.name %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p class='lead'>
          Thank you for claiming this wishlist! Please check your email for confirmation and additional details.<br>If you'd like to sponsor additional wishlists, click below.
        </p>
      <% end %>
    </div>
    <div class='card-footer'>
      <% if @list.sponsor.present? %>
        <%= link_to 'View All Wishlists', event_lists_path(@event), class: 'btn btn-primary btn-lg d-block' %>
      <% else %>
        <%= link_to 'Claim Wishlist', claim_event_list_path(@event, @list), class: 'btn btn-primary btn-lg d-block' %>
      <% end %>
    </div>
  </div>
</div>