config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" unless Rails.env.production?

  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    unlocks:            'users/unlocks',
    passwords:          'users/passwords'
  }

  resources :events do
    resources :lists, only: [:index, :show] do
      collection do
        get :feed
      end

      member do
        get :claim
      end
    end
    
    resources :families do
      member do
        put :lists_complete
        get :confirmation
      end

      resources :lists
    end

  end

  resources :sponsors

  namespace :admin do
    resource :settings
    resources :sponsors
    resources :users, only: [:index]
    resources :ahoy_visits, only: [:index], path: 'visits'
    resources :ahoy_events, only: [:index], path: 'ahoy_events'
    resources :events do
      member do 
        get :cheatsheet
      end
    end
    resources :lists do
      member do
        put :remove_sponsor
      end
    end
    resources :list_items
    resources :families
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
end

app/models/ahoy/event.rb
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :user, optional: true

  scope :recent, -> { where('time > ?', 1.week.ago).order(time: :desc) }
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :families, dependent: :destroy
  has_many :lists,    through: :families
  has_many :sponsors, -> { distinct.order('sponsors.full_name ASC') }, through: :lists
  
  validates :name,        presence: true
  validates :description, presence: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_action :set_event, only: %i[ show edit cheatsheet update destroy ]

  def index
    @page_title = "Events"
    @events     = Event.all
  end

  def show
    @page_title = @event.name
    @association_name = params[:association].present? ? params[:association] : 'families'
    @association      = @event.send(@association_name)
  end

  def cheatsheet
  end

  def new
    @page_title = "New Event"
    @event = Event.new
  end

  def edit
    @page_title = "Edit Event"
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_event_url(@event), notice: "Event was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to admin_event_url(@event), notice: "Event was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: "Event was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(
        :name,
        :description,
        :slug
      )
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show ]

  def index
    @page_title = "Events"
    @events     = Event.all

    redirect_to new_event_family_path(@events.first) if @events.count == 1
  end

  def show
    @page_title       = @event.name
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= event.slug %>
  </p>

  <p>
    <strong>Family Wishlist Creation Url (<%= link_to 'Go', new_event_family_url(event), target: :_blank %>):</strong><br>
    <pre><%= new_event_family_url(event) %></pre>
  </p>

  <p>
    <strong>Public Sponsor Url (<%= link_to 'Go', event_lists_url(event), target: :_blank %>):</strong><br>
    <pre><%= event_lists_url(event) %></pre>
  </p>

  <p>
    <label>Families Count:</label>
    <%= event.families.count %>
  </p>

  <p>
    <label>Sponsors Count:</label>
    <%= event.sponsors.count %>
  </p>

  <p>
    <label>Wishlists Count:</label>
    <%= event.lists.count %>
  </p>

  <ul class="nav mb-3">
    <% ['families', 'sponsors', 'lists'].each do |tab| %>
      <li class="nav-item">
        <%= link_to "#{tab.titleize} (#{event.send(tab).count})", url_for(association: tab), class: "nav-link #{tab == @association_name ? 'active' : ''}" %>
      </li>
    <% end %>
  </ul>

  <%= render "admin/#{@association_name}/table", @association_name.to_sym => @association %>

</div>

app/views/admin/events/_form.html.erb
<%= simple_form_for([:admin, @event]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class='field'>
      <%= f.input :name, input_html: { class: 'form-control' } %>
    </div>

    <div class='field'>
      <%= f.input :description, input_html: { class: 'form-control' } %>
    </div>

    <% unless @event.new_record? %>
      <div class='field'>
        <%= f.input :slug, input_html: { class: 'form-control' } %>
      </div>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/events/cheatsheet.html.erb
<% @event.families.each do |family| %>
  <section class='border-bottom mb-3 py-3'>
    <h2 class='h4'><%= family.name %></h2>

    <section class='ps-3'>
      <% family.lists.each do |list| %>
        <h3 class='h5'><%= list.name %> (alias: <%= list.alias %>)</h3>
        <% if list.sponsor.present? %>
          <p class=''>Sponsor: <%= list.sponsor&.full_name %></p>
        <% end %>

        <ul class='list-unstyled'>
          <% list.list_items.each do |list_item| %>
            <li>
              <i class='fa fa-square-o'></i>
              <%= list_item.name %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </section>
  </section>
<% end %>

app/views/admin/events/edit.html.erb
<%= render "form", event: @event %>

app/views/admin/events/index.html.erb
<%= content_for :page_actions do %>
  <%= link_to "New event", new_admin_event_path, class: 'btn btn-primary' %>
<% end %>

<div id="events">
  <table class='table'>
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td>
            <%= link_to event.name, admin_event_path(event) %>
          </td>
          <td class='text-end'>
            <div class="dropdown">
              <button class="btn btn-outline-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Actions
              </button>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "Edit", edit_admin_event_path(event), class: 'dropdown-item' %>
                </li>
                <li>
                  <%= link_to "View", admin_event_path(event), class: 'dropdown-item' %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/events/new.html.erb
<%= render "form", event: @event %>

app/views/admin/events/show.html.erb
<%= content_for :page_actions do %>
  <%= link_to 'Cheatsheet', cheatsheet_admin_event_path(@event), class: 'btn btn-primary' %>
<% end %>

<%= render @event %>