config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" unless Rails.env.production?

  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    unlocks:            'users/unlocks',
    passwords:          'users/passwords'
  }

  resources :events do
    resources :lists, only: [:index, :show] do
      collection do
        get :feed
      end

      member do
        get :claim
      end
    end
    
    resources :families do
      member do
        put :lists_complete
        get :confirmation
      end

      resources :lists
    end

  end

  resources :sponsors

  namespace :admin do
    resource :settings
    resources :sponsors
    resources :users, only: [:index]
    resources :ahoy_visits, only: [:index], path: 'visits'
    resources :ahoy_events, only: [:index], path: 'ahoy_events'
    resources :events do
      member do 
        get :cheatsheet
      end
    end
    resources :lists do
      member do
        put :remove_sponsor
      end
    end
    resources :list_items
    resources :families
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
end

app/models/family.rb
class Family < ApplicationRecord
  include PgSearch::Model
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :event

  has_many :lists, dependent: :destroy

  scope :pending,           -> { where(lists_completed_at: nil) }
  scope :completed,         -> { where.not(lists_completed_at: nil) }
  scope :support_requested, -> { where(is_support_requested: true) }

  pg_search_scope :contains,
                  against: [
                    :name,
                    :phone,
                    :email,
                    :address
                  ],
                  using: { tsearch: { prefix: true } }

  validates :name,    presence: true
  validates :phone,   presence: true
  validates :email,   presence: true
  validates :address, presence: true
  
  def lists_count
    lists.count
  end

  def event_name
    event&.name
  end

  def self.to_csv
    attrs = [
      "id",
      "name",
      "phone",
      "email",
      "address",
      "event_name",
      "holiday",
      "wrap_gifts",
      "is_support_requested",
      "is_attending",
      "attendance_selection",
      "lists_count",
      "household_caregivers_count",
      "household_children_count",
      "slug",
      "created_at",
      "lists_completed_at",
    ]

    CSV.generate do |csv|
      csv << attrs
    
      all.each do |family|
        csv << attrs.map {|attr| family.send(attr)}
      end
    end
  end
end

app/controllers/admin/families_controller.rb
class Admin::FamiliesController < Admin::BaseController
  before_action :_set_family, only: [:show, :edit, :update, :destroy]

  def index
    @page_title = "Families"
    @families   = Family.all
    @families   = @families.send(params[:scope]) if params[:scope].present?
    @families   = @families.contains(params[:q]) if params[:q].present?

    respond_to do |format|
      format.html
      format.csv { send_data @families.to_csv }
    end
  end

  def show
    @page_title = @family.name
  end

  def edit
    @page_title = 'Edit Family'
    @family     = Family.friendly.find(params[:id])
  end

  def update
    if @family.update(family_params)
      redirect_to admin_families_path, notice: "Family updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @family.destroy

    redirect_url = params[:redirect_url].present? ? params[:redirect_url] : admin_families_path
    redirect_to redirect_url, notice: "Family deleted successfully"
  end

  private

  def _set_family
    @family = Family.friendly.find(params[:id])
  end

end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :_set_event
  before_action :set_family, only: %i[ show edit update lists_complete confirmation destroy ]

  def index
    @page_title = "Families"
    @families   = Family.all
  end

  def show
    @page_title = @family.name
  end

  def new
    @page_title = "New Family"
    @family     = Family.new
  end

  def edit
    @page_title = "Edit Family"
  end

  def lists_complete
    if @family.update(lists_completed_at: Time.current)
      FamilyMailer.confirmation_email(@family.id).deliver_now
      redirect_to confirmation_event_family_path(@family.event, @family), notice: "Your wishlists are complete."
    else
      redirect_to event_family_confirmation_path(@family.event, @family), alert: "There was an error."
    end
  end

  def confirmation
    @page_title = "Confirmation"
  end

  def create
    @family       = @event.families.new(family_params)
    @family.event = @event

    respond_to do |format|
      if @family.save
        redirect_url = @family.is_support_requested ? new_event_family_list_path(@family.event, @family) : confirmation_event_family_path(@family.event, @family)
        format.html { redirect_to redirect_url, notice: "Family was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to event_family_url(@family.event, @family), notice: "Family was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @family.destroy

    respond_to do |format|
      format.html { redirect_to families_url, notice: "Family was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def family_params
      params.require(:family).permit(
        :name,
        :phone,
        :email,
        :address,
        :holiday,
        :wrap_gifts,
        :household_caregivers_count,
        :household_children_count,
        :slug,
        :is_attending,
        :is_support_requested,
        :attendance_selection
      )
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_family.html.erb
<div id="<%= dom_id family %>">
  <p>
    <strong>Name:</strong>
    <%= family.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= family.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= family.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= family.address %>
  </p>

  <p>
    <strong>Holiday:</strong>
    <%= family.holiday %>
  </p>

  <p>
    <strong>Wrap gifts:</strong>
    <%= family.wrap_gifts %>
  </p>

  <p>
    <strong>Household caregivers count:</strong>
    <%= family.household_caregivers_count %>
  </p>

  <p>
    <strong>Household children count:</strong>
    <%= family.household_children_count %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= family.slug %>
  </p>

</div>

app/views/families/_form.html.erb
<%= simple_form_for([@event, @family]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  
  <div class='card'>
    <% if defined?(title) %>
      <div class='card-header'>
        <h1><%= title %></h1>
      </div>
    <% end %>

    <div class='card-body'>
      <% if defined?(description) %>
        <p><%== description %></p>
      <% end %>

      <div class='field'>
        <%= f.input :name, input_html: { class: 'form-control' }, label: 'Your Name' %>
      </div>

      <div class='field'>
        <%= f.input :phone, input_html: { class: 'form-control' }, label: 'Your Phone Number' %>
      </div>

      <div class='field'>
        <%= f.input :email, input_html: { class: 'form-control' }, label: 'Your Email' %>
      </div>

      <div class='field'>
        <%= f.input :address, input_html: { class: 'form-control' }, label: 'County of Residence', collection: ['Cobb', 'Paulding', 'Fulton', 'DeKalb', 'Cherokee', 'Gwinnett', 'Forsyth', 'Rockdale', 'Henry', 'Clayton', 'Douglas', 'Other'], include_blank: 'Select a County' %>
      </div>

      <div class='field'>
        <%= f.input :holiday, input_html: { class: 'form-control' }, label: 'What Holiday do you celebrate?' %>
      </div>

      <div class='field'>
        <%= f.input :wrap_gifts, collection: ['Yes, please wrap my gifts', "I'll wrap them myself - please provide a roll of wrapping paper."], as: :select, input_html: { class: 'form-control' }, label: 'Would you like the gifts wrapped?', include_blank: false %>
      </div>

      <div class='field'>
        <%= f.input :household_caregivers_count, collection: 1..4, input_html: { class: 'form-control' }, label: "How many caregivers are in the home?", include_blank: false %>
      </div>

      <div class='field'>
        <%= f.input :household_children_count, collection: 0..10, input_html: { class: 'form-control' }, label: "How many children are in the home?", include_blank: false %>
      </div>

      <% if false %>
        <div class='field'>
          <%= f.input :is_attending, as: :radio_buttons, collection: [ 
            'Yes, on Saturday, December 7 at Roswell Movie Tavern at 10am.',
            'Yes, on Sunday, December 8 at Tucker Movie Tavern at 10am.',
            'I will not be able to make it.',
            'I am not sure.' ], label: 'Will your family be joining us at our annual holiday party?', input_html: { class: '' }, hint: 'There will be two separate holiday party options in different areas of Atlanta. Each will have the same movie showings with wishlist items, activities, and one large popcorn per household. Please choose the event day and movie showing that works best for your household!', include_blank: false %>
        </div>

        <div class='field' id='attendance_selection_wrapper'>
          <%= f.input :attendance_selection, collection: ['Elf', 'Moana 2', 'The Best Christmas Pageant Ever'], label: 'If Yes, which movie would you and your family like to watch?', input_html: { class: 'form-control' }, include_blank: false %>
        </div>
      <% end %>

      <div class='field'>
        <%= f.input :is_support_requested, label: 'Do you need support with gifts for children in care?', collection: {'Yes' => true, 'No' => false}, input_html: { class: 'form-control' }, include_blank: false %>
      </div>

      <% unless @family.new_record? %>
        <div class='field'>
          <%= f.input :slug, input_html: { class: 'form-control' } %>
        </div>
      <% end %>
    </div>

    <div class='card-footer'>
      <%= f.button :submit, class: 'btn btn-primary btn-lg w-100' %>
    </div>
  </div>
<% end %>

app/views/families/confirmation.html.erb
<div id="<%= dom_id @family %>" class='container w-md'>
  <div class='card'>
    <div class='card-header'>
      <h1>You're Done</h1>
    </div>
    <div class='card-body'>
      <p>
        Your holiday wishlists have been completed!
      </p>

      <p>
        Thank you for providing information so we can support your family in celebrating the holidays this year.
        If you have any questions or changes, please contact our Lead Program Coordinators Allie <%= mail_to 'allie@atlantaangels.org' %> and Muniza <%= mail_to 'muniza@atlantaangels.org' %>.
      </p>
    </div>
  </div>
</div>

app/views/families/edit.html.erb
<h1>Editing family</h1>

<%= render "form", family: @family %>

<br>

<div>
  <%= link_to "Show this family", @family %> |
  <%= link_to "Back to families", families_path %>
</div>

app/views/families/index.html.erb
<h1>Families</h1>

<div id="families">
  <% @families.each do |family| %>
    <%= render family %>
    <p>
      <%= link_to "Show this family", family %>
    </p>
  <% end %>
</div>

<%= link_to "New family", new_family_path, class: 'btn btn-primary' %>

app/views/families/new.html.erb
<div class='container w-md'>
  <%= render "form", family: @family, title: 'Holiday Extravaganza 2025 - Wishlists', description: "<b>Happy Holiday Season!</b><br><br> We’re thrilled to continue supporting all of our families this year.<br><br>As part of our holiday giving, every household will receive a Holiday Love Box, filled with items to help create joyful traditions and special moments for everyone in your home.<br><br>We can’t wait to celebrate the season together!" %>
</div>

app/views/families/show.html.erb
<div id="<%= dom_id @family %>" class='container w-md'>
  <h1>Confirmed family</h1>
  <p>
    <strong>Name:</strong>
    <%= @family.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @family.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @family.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @family.address %>
  </p>

  <p>
    <strong>Holiday:</strong>
    <%= @family.holiday %>
  </p>

  <p>
    <strong>Wrap gifts:</strong>
    <%= @family.wrap_gifts %>
  </p>

  <p>
    <strong>Household caregivers count:</strong>
    <%= @family.household_caregivers_count %>
  </p>

  <p>
    <strong>Household children count:</strong>
    <%= @family.household_children_count %>
  </p>
</div>