config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" unless Rails.env.production?

  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    unlocks:            'users/unlocks',
    passwords:          'users/passwords'
  }

  resources :events do
    resources :lists, only: [:index, :show] do
      collection do
        get :feed
      end

      member do
        get :claim
      end
    end
    
    resources :families do
      member do
        put :lists_complete
        get :confirmation
      end

      resources :lists
    end

  end

  resources :sponsors

  namespace :admin do
    resource :settings
    resources :sponsors
    resources :users, only: [:index]
    resources :ahoy_visits, only: [:index], path: 'visits'
    resources :ahoy_events, only: [:index], path: 'ahoy_events'
    resources :events do
      member do 
        get :cheatsheet
      end
    end
    resources :lists do
      member do
        put :remove_sponsor
      end
    end
    resources :list_items
    resources :families
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  include PgSearch::Model
  extend FriendlyId
  friendly_id :_sluggable, use: :slugged

  has_many :lists

  attr_accessor :redirect_url

  scope :without_lists, -> { includes(:lists).where(lists: { id: nil }) }
  scope :with_lists,    -> { includes(:lists).where.not(lists: { id: nil }) }

  pg_search_scope :contains,
                  against: [
                    :full_name,
                    :email,
                    :phone,
                    :address,
                  ],
                  using: { tsearch: { prefix: true } }

  validates :full_name, presence: true
  validates :email,     presence: true
  validates :address,   presence: true

  def self.to_csv
    attrs = [
      "id",
      "full_name",
      "email",
      "phone",
      "address",
    ]

    CSV.generate do |csv|
      csv << attrs
    
      all.each do |family|
        csv << attrs.map {|attr| family.send(attr)}
      end
    end
  end

  def _sluggable
    SecureRandom.uuid
  end
end

app/controllers/admin/sponsors_controller.rb
class Admin::SponsorsController < Admin::BaseController
  before_action :set_sponsor, only: %i[ show edit update destroy ]

  def index
    @page_title    = "Sponsors"
    @sponsors      = Sponsor.all
    @sponsors      = @sponsors.send(params[:scope]) if params[:scope].present?
    @sponsors      = @sponsors.contains(params[:q]) if params[:q].present?

    respond_to do |format|
      format.html
      format.csv { send_data @sponsors.to_csv }
    end
  end

  def show
    @page_title = @sponsor.full_name
  end

  def edit
  end

  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to sponsor_url(@sponsor), notice: "Sponsor was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to sponsors_url, notice: "Sponsor was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sponsor_params
      params.require(:sponsor).permit(:full_name, :email, :phone, :address, :redirect_url)
    end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: %i[ show edit update destroy ]

  def index
    @sponsors = Sponsor.all
  end

  def show
  end

  def new
    @sponsor = Sponsor.new(redirect_url: session[:redirect_url])
  end

  def edit
  end

  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        session[:sponsor_id] = @sponsor.id
        format.html { redirect_to @sponsor.redirect_url, notice: "Sponsor was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to sponsor_url(@sponsor), notice: "Sponsor was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to sponsors_url, notice: "Sponsor was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sponsor_params
      params.require(:sponsor).permit(:full_name, :email, :phone, :address, :redirect_url)
    end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/admin/sponsors/_actions.html.erb
<div class="dropdown">
  <button class="<%= defined?(btn_classes) ? btn_classes : 'btn btn-outline-primary btn-sm' %> dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Actions
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to 'Edit Sponsor', edit_admin_sponsor_path(sponsor), class: 'dropdown-item' %></li>
    <li><%= link_to 'View Sponsor', [:admin, sponsor], class: 'dropdown-item' %></li>
    <% if false %>
      <li><hr class="dropdown-divider"></li>
      <li><%= link_to 'Delete Sponsor', admin_sponsor_path(sponsor, redirect_url: url_for()), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger dropdown-item' %></li>
    <% end %>
  </ul>
</div>

app/views/admin/sponsors/_form.html.erb
<%= simple_form_for(@sponsor) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :redirect_url, as: :hidden %>
  <div class="form-inputs">
    <div class='field'>
      <%= f.input :full_name, input_html: { class: 'form-control' } %>
    </div>

    <div class='field'>
      <%= f.input :email, input_html: { class: 'form-control' } %>
    </div>

    <div class='field'>
      <%= f.input :phone, input_html: { class: 'form-control' } %>
    </div>

    <div class='field'>
      <%= f.input :address, input_html: { class: 'form-control' } %>
    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Save & Continue', class: 'btn btn-primary btn-lg w-100' %>
  </div>
<% end %>

app/views/admin/sponsors/_sponsor.html.erb
<div id="<%= dom_id sponsor %>">
  <p>
    <strong>Full name:</strong>
    <%= sponsor.full_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= sponsor.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= sponsor.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= sponsor.address %>
  </p>

</div>

app/views/admin/sponsors/_table.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th class='text-center'>Wishlists</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% sponsors.each do |sponsor| %>
      <tr>
        <td>
          <%= sponsor.full_name %>
        </td>
        <td>
          <%= sponsor.email %>
        </td>
        <td class='text-center'>
          <%= sponsor.lists.count %>
        </td>
        <td class='text-end'>
          <%= render 'admin/sponsors/actions', sponsor: sponsor %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/sponsors/edit.html.erb
<h1>Editing sponsor</h1>

<%= render "form", sponsor: @sponsor %>

<br>

<div>
  <%= link_to "Show this sponsor", @sponsor %> |
  <%= link_to "Back to sponsors", sponsors_path %>
</div>

app/views/admin/sponsors/index.html.erb
<div class='row mb-4'>
  <div class='col-sm-6'>
    <ul class="nav nav-pills">
      <% ['all', 'without_lists', 'with_lists'].each do |scope| %>
        <li class="nav-item">
          <% if scope == 'all' %>
            <%= link_to scope.titleize, url_for(scope: nil), class: "nav-link #{params[:scope].nil? ? 'active' : ''}" %>
          <% else %>
            <%= link_to scope.titleize, url_for(scope: scope), class: "nav-link #{scope == params[:scope] ? 'active' : ''}" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class='col-sm-6 text-end'>
    <%= link_to "Export to CSV", url_for(format: "csv"), class: "btn btn-outline-secondary" %>
    <div class='d-inline-block'>
      <%= render 'shared/search' %>
    </div>
  </div>
</div>

<%= render 'table', sponsors: @sponsors %>

app/views/admin/sponsors/new.html.erb
<div class='container w-md'>
  <h1>Enter Your Information</h1>

  <%= render "form", sponsor: @sponsor %>
</div>

app/views/admin/sponsors/show.html.erb
<%= render @sponsor %>

<% if @sponsor.lists.present? %>
  <h2>Wishlists</h2>
  <%= render 'admin/lists/table', lists: @sponsor.lists %>
<% end %>